max_ip_limit = 100

[grpc]
grpc_addr = "[::1]:10000"

[nats]
nats_url = "nats://localhost:4222"

[database]
database_url = "postgres://localhost:5432/arkvote"
max_connections = 20

[redis]
redis_url = "redis://localhost:6379/0"
max_connections = 20

[snowflake]
worker_id = 1
datacenter_id = 1

[dlq]
dlq_subject = "vote.dlq"
max_retry_attempts = 5
